apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-ephemeral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment-ephemeral
  template:
    metadata:
      labels:
        app: mysql-deployment-ephemeral
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: UseASecretInstead
            - name: MYSQL_DATABASE
              value: mydb
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
